// flow-typed signature: 9edb2b5d29d23c244b4b7443b8041221
// flow-typed version: <<STUB>>/tap-nyan_v^1.1.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tap-nyan'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tap-nyan' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tap-nyan/bin/cmd' {
  declare module.exports: any;
}

declare module 'tap-nyan/bin/nyan' {
  declare module.exports: any;
}

declare module 'tap-nyan/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tap-nyan/bin/cmd.js' {
  declare module.exports: $Exports<'tap-nyan/bin/cmd'>;
}
declare module 'tap-nyan/bin/nyan.js' {
  declare module.exports: $Exports<'tap-nyan/bin/nyan'>;
}
declare module 'tap-nyan/index' {
  declare module.exports: $Exports<'tap-nyan'>;
}
declare module 'tap-nyan/index.js' {
  declare module.exports: $Exports<'tap-nyan'>;
}
declare module 'tap-nyan/test/test.js' {
  declare module.exports: $Exports<'tap-nyan/test/test'>;
}
